### PR TITLE
Unified Docker Config keys

### PR DESCRIPTION
**Pull request by VariableDeclared**
Changed all relevant underscored keys to hyphens for consistency.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
+1 for trying to have a single format. I am wondering if we can do this switch like so, or of we need to take into account backwards compatibility.

**Comment by Cynerva** [comment]
This trades one form of inconsistency (config keys are formatted differently) for another (config keys are different between releases). When someone upgrades, they will lose config values that they have previously set. Documentation and scripts will need to be updated too. I don't think it's worth it.

**Comment by VariableDeclared** [comment]
@Cynerva I understand the implications of this. As advised will request a feature for this.

**Comment by kwmonroe** [comment]
@VariableDeclared - i like your request for a Juju way to alias config (https://bugs.launchpad.net/juju/+bug/1833094).  That would solve the issue for a lot more charms than just those built for layer-docker.

I agree with @Cynerva, so I'm closing this out to make sure it's not accidentally merged.  That said, thanks for this effort -- let's see if we can get a more generic Juju way to do this.

**Pull request closed without merging**
