### PR TITLE
Adds series in Metadata

### PR DESCRIPTION
**Pull request by chuckbutler**

### CODE REVIEW

**Comment by mbruzek** [comment]
This does not work with 1.25.4 yet and we should test the crap out of it on 1.25.5 before merging this.

**Comment by arosales** [comment]
I think in current 1.25.x this should work properly. I'll have to set up a 1.25 environment to test unless other folks have confirmed this.

Also is the kube-up script locked to any old version of Juju 1.25?

-thanks,
Antonio

**Comment by chuckbutler** [comment]
@arosales no, it's actually targeting juju 2.0 very early, and does not work on 1.25 environments

**Comment by arosales** [comment]
@chuckbutler agreed it doesn't work in 1.25.x, but I wanted to comment that juju-core shouldn't error on these additional values just ignore them. If this is indeed the case I think this is safe to merge.

**Comment by chuckbutler** [comment]
Yep, we're safe i just tested in stable charm box and it works as expected.

**Pull request merged**
