### PR TITLE
This + #40 should fix dockerpy issues

### PR DESCRIPTION
**Pull request by chuckbutler**

### CODE REVIEW

**Comment by johnsca** [comment]
You should include the version of setuptools that you want in your `wheelhouse.txt` and install from there.  Otherwise, you're making any charm using this layer require access to pypi where it wouldn't otherwise.

**Comment by mbruzek** [comment]
@johnsca We tried adding setuptools in the wheelhouse but as you pointed out there was no way to order the installs, and we got an installation error.

**Comment by johnsca** [comment]
@mbruzek No, I mean that you should put setuptools in the wheelhouse *and* have the exec.d script install it (from the wheelhouse).  IOW, do what this PR is doing, but do it from the wheelhouse to prevent network access.

**Comment by chuckbutler** [comment]
Marking this as help wanted to remind myself to circle back and look at charm-tools and custom tactics so we can properly close this bug once those are GA and we can use the custom wheelhouse tactic.

**Pull request closed without merging**
