### PR TITLE
Fix missing custom Docker daemon options in systemd

### PR DESCRIPTION
**Pull request by simonklb**
Hotfix for https://github.com/juju-solutions/layer-docker/issues/21

### CODE REVIEW

**Comment by simonklb** [comment]
No objections here. I'm all in favor of getting rid of the install script.

**Comment by mbruzek** [comment]
I concur with @chuckbutler, using the archive by default will be much easier to maintain. If you want the latest docker can template that install.

Since this change is systemd __only__ we should detect release version when installed on upstart systems (Ubuntu 14.04 trusty is upstart).

**Comment by chuckbutler** [comment]
This branch also has conflicts :(  🚑 

Do you mind rebasing and re-submitting @simonklb?

**Comment by simonklb** [comment]
Absolutely!

**Comment by chuckbutler** [comment]
:sail: bon voyage "no systemd support"

**Pull request merged**
