### PR TITLE
Change charms to use juju-http{s}-proxy model settings

### PR DESCRIPTION
**Pull request by VariableDeclared**
Changed charm to use juju-http{s}-proxy-settings when these keys are defined.

[LP#1831712](https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1831712)

### CODE REVIEW

**Comment by VariableDeclared** [comment]
Pending Jenkins Tests
[#7](https://github.com/charmed-kubernetes/charm-docker/pull/7)
[#8](https://github.com/charmed-kubernetes/charm-containerd/pull/8)

**Comment by VariableDeclared** [comment]
Added Jenkins Tests; [#447](https://github.com/charmed-kubernetes/jenkins/pull/447/files)

**Comment by Cynerva** [comment]
Re-iterating my comments on other PRs here.
* Don't write to `config()`: https://github.com/charmed-kubernetes/charm-docker/pull/7#discussion_r303070009
* Is CIDR notation supported?: https://github.com/charmed-kubernetes/charm-docker/pull/7#issuecomment-510967105

**Comment by Cynerva** [comment]
We don't use layer-docker in CDK anymore. Can we stop maintaining it?

**Comment by tvansteenburgh** [comment]
> We don't use layer-docker in CDK anymore. Can we stop maintaining it?

Yes.

**Comment by Cynerva** [comment]
Per https://bugs.launchpad.net/layer-docker-registry/+bug/1832336, it looks like we do actually still use layer-docker in the docker-registry charm. So we may need to reconsider this PR after all.

Sorry, that was a bad call on my part.

**Pull request closed without merging**
